{
    'name': 'Cash Book, Day Book, Bank Book Financial Reports',
    'version': '17.0.1.1',
    'category': 'Invoicing Management',
    'summary': 'Cash Book, Day Book and Bank Book Report For Odoo 17',
    'description': 'Cash Book, Day Book and Bank Book Report For Odoo 17',
    'sequence': '10',
    'depends': ['account', 'accounting_pdf_reports'],
    'depends': ['account', 'accounting_pdf_reports'],
    'data': [
        'security/ir.model.access.csv',
        'views/om_daily_reports.xml',
        'wizard/daybook.xml',
        'wizard/cashbook.xml',
        'wizard/bankbook.xml',
        'report/reports.xml',
        'report/report_daybook.xml',
        'report/report_cashbook.xml',
        'report/report_bankbook.xml',
    ],
    'images': ['static/description/banner.gif'],
}
